import { app, BrowserWindow, ipcMain, shell } from 'electron';
import { ICON, MIN_WIDTH, MIN_HEIGHT, HIDE_MENU, AUTHOR_URL } from '@constants/index';
import createTray from '@main/tray';
import BulbManager from '@main/BulbManager';
// import installExtension, { REACT_DEVELOPER_TOOLS } from 'electron-devtools-installer';

import checkForUpdates from '@main/updater';
import log from 'electron-log';
import initializeLogger from '@main/logger';
import initializeLanguage from '@main/language';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

initializeLogger();
initializeLanguage(app);

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: MIN_HEIGHT,
    width: MIN_WIDTH,
    minWidth: MIN_WIDTH,
    minHeight: MIN_HEIGHT,
    icon: ICON,
    autoHideMenuBar: HIDE_MENU,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: !app.isPackaged,
    },
  });

  checkForUpdates(app);

  const bulbHelper = new BulbManager(mainWindow);
  createTray(mainWindow, app, bulbHelper);

  ipcMain.on('toggle-bulb-state', async () => {
    await bulbHelper.toggleBulb();
  });

  ipcMain.on('visit-author', () => {
    shell.openExternal(AUTHOR_URL);
  });

  ipcMain.on('set-brightness', async (event, brightness) => {
    await bulbHelper.setBrightness(brightness);
  });

  ipcMain.on('set-bulb-name', async (event, name) => {
    await bulbHelper.setBulbName(name);
  });

  //TODO: TEST!
  ipcMain.on('set-ip', async (event, ip) => {
    await bulbHelper.setIp(ip);
  });

  ipcMain.on('set-scene', async (event, sceneId) => {
    await bulbHelper.setScene(sceneId);
  });

  ipcMain.on('add-custom-color', async (event, colorName, colorHex) => {
    await bulbHelper.addCustomColor(colorName, colorHex);
  });

  ipcMain.on('set-custom-color', async (event, colorId) => {
    await bulbHelper.setCustomColor(colorId);
  });

  ipcMain.on('edit-color', async (event, colorId, colorName, colorHex) => {
    await bulbHelper.editCustomColor(colorId, colorName, colorHex);
  });

  ipcMain.on('remove-color', async (event, colorId) => {
    await bulbHelper.removeCustomColor(colorId);
  });

  ipcMain.handle('get-bulb', () => {
    return bulbHelper.getBulbState();
  });

  ipcMain.handle('get-version', () => {
    return app.getVersion();
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  mainWindow.on('close', () => {
    log.info('Closing app...');
    bulbHelper.endConnection();
  });

  mainWindow.on('minimize', () => {
    log.info('Hiding app to tray...');
    log.debug('Window size is:', mainWindow.getSize());
    mainWindow.hide();
  });
};

const gotTheLock = app.requestSingleInstanceLock();
if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', () => {
    const mainWindow = BrowserWindow.getAllWindows()[0];
    if (mainWindow) {
      if (mainWindow.isMinimized()) {
        mainWindow.show();
      }
      mainWindow.focus();
    }
  });

  app.setName('WiZ App');

  // This method will be called when Electron has finished
  // initialization and is ready to create browser windows.
  // Some APIs can only be used after this event occurs.
  app.on('ready', createWindow);
}

/* app.whenReady().then(() => {
  installExtension(REACT_DEVELOPER_TOOLS)
    .then((name) => {
      console.log(`Added Extension:  ${name}`);
    })
    .catch((err) => {
      console.log('An error occurred: ', err);
    });
}); */

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
