# .github/workflows/release.yml
name: Release app
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    environment: release
    runs-on: windows-latest
    steps:
      - name: Github checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish
